#!/bin/sh

# Utilities
alias c="bat"
alias gits="git status"
alias l="exa -al"
alias zzz="source ~/.zshrc"
alias zzv="vim ~/.zshrc"

# Kubernetes and Docker
alias k="kubectl"
alias d="docker"

# Pueue
alias p="pueue"
alias pa="pueue add"
alias pst="pueue status"
alias prt="pueue reset"
alias pls="pueue log"
alias pf="pueue follow"

